### ISSUE TITLE
Iteration 1 Fix - Visits

### ISSUE THREAD

**Issue by jburton6** [mstudar1/clinic#40] opened 2021-04-09 23:51 UTC
New visit: -1

- [x] the nurse should be automatically filled in (whoever is logged in)
- [x] the error message is unclear as to which field is not in a correct format. It’s better to show detailed information so that the user knows which field is wrong and what’s expected. An error label next to each field is a more user-friendly approach to display errors. 

Visits: -3

- [x] same issue as in appointments. Search needs to be able to narrow down to a specific patient.
- [x] search visits doesn’t work for the patient that I added(see image2). There is a visit added to patient with last name Doe (see in the DB), but it doesn’t show it in the GUI. I tried last name Cat, it worked. I tried your SQL without any last name, it doesn’t retrieve the visits that I added at all. Why?

**Comment by mstudar1** [comment] 2021-04-15 00:13
As a part of the first task, I modified the 'begin visit' button on the appointments tab so that it is only enabled for nurses.

**Comment by mstudar1** [comment] 2021-04-15 01:38
I merged the first two tasks (the ones under the heading of 'new visit') into master from the 'issue40' branch.  I will use a separate branch for the remaining tasks.

**Comment by mstudar1** [comment] 2021-04-16 16:41
The last issue was caused by an error in the SQL query.  One of the join statements in each query mistakenly referred to the nurseId instead of the personId.  This issue was fixed with commit c54c3372.

**Closed as completed by mstudar1** 2021-04-16 16:41 UTC
